CruceoPortalBundle:
    resource: "@CruceoPortalBundle/Resources/config/routing.yml"
    prefix:   /
    
CruceoUserBundle:
    resource: "@CruceoUserBundle/Resources/config/routing.yml"
    prefix:   /

CruceoPortalBundle_admin_ciudades:
    resource: "@CruceoUserBundle/Resources/config/routing/ciudades.yml"
    prefix:   /admin/ciudades

CruceoPortalBundle_admin_navieras:
    resource: "@CruceoUserBundle/Resources/config/routing/navieras.yml"
    prefix:   /admin/navieras

CruceoPortalBundle_admin_zonas:
    resource: "@CruceoUserBundle/Resources/config/routing/zonas.yml"
    prefix:   /admin/zonas

CruceoPortalBundle_admin_categorias:
    resource: "@CruceoUserBundle/Resources/config/routing/categorias.yml"
    prefix:   /admin/categorias

CruceoPortalBundle_admin_agencias:
    resource: "@CruceoUserBundle/Resources/config/routing/agencias.yml"
    prefix:   /admin/agencias

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
