jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Cruceo\UserBundle\Entity\BackUser:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    providers:
        administrators:
            entity: { class: CruceoUserBundle:BackUser }

    firewalls:
        login:
            pattern: ^/admin/login$
            security: false

        #newuser:
        #    pattern:  ^/newuser
        #    security: false

        admin_area:
            pattern:    ^/admin
            #http_basic:
            #    realm:    "Admin Cruceo"
            #    provider: administrators
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin
            logout:
                path:   /admin/logout
                target: /admin/login

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
