security:
    encoders:
        Cruceo\UserBundle\Entity\BackUser:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    providers:
        administrators:
            entity: { class: CruceoUserBundle:BackUser }

    firewalls:
        admin_area:
            pattern:    ^/admin
            http_basic:
                realm:    "Admin Cruceo"
                provider: administrators
        newuser:
            pattern:  ^/newuser
            security: false

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
