admin_agencias:
    pattern:  /
    defaults: { _controller: "CruceoUserBundle:Agencias:index" }

admin_agencias_new:
    pattern:  /new
    defaults: { _controller: "CruceoUserBundle:Agencias:new" }

admin_agencias_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CruceoUserBundle:Agencias:edit" }

admin_agencias_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CruceoUserBundle:Agencias:delete" }
    requirements: { _method: post }
