admin_categorias:
    pattern:  /
    defaults: { _controller: "CruceoUserBundle:Categorias:index" }

admin_categorias_new:
    pattern:  /new
    defaults: { _controller: "CruceoUserBundle:Categorias:new" }

admin_categorias_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CruceoUserBundle:Categorias:edit" }

admin_categorias_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CruceoUserBundle:Categorias:delete" }
    requirements: { _method: post }
