admin_cruceros:
    pattern:  /
    defaults: { _controller: "CruceoUserBundle:Cruceros:index" }

admin_cruceros_new:
    pattern:  /new
    defaults: { _controller: "CruceoUserBundle:Cruceros:new" }

admin_cruceros_create:
    pattern:  /create
    defaults: { _controller: "CruceoUserBundle:Cruceros:create" }
    requirements: { _method: post }

admin_cruceros_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CruceoUserBundle:Cruceros:edit" }

admin_cruceros_update:
    pattern:  /{id}/update
    defaults: { _controller: "CruceoUserBundle:Cruceros:update" }
    requirements: { _method: post }

admin_cruceros_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CruceoUserBundle:Cruceros:delete" }
    requirements: { _method: post }
    
admin_cruceros_delete_itinerario:
    pattern:  /img/{img}/remove
    defaults: { _controller: "CruceoUserBundle:Cruceros:deleteImage", _format: json|html }
    requirements: { _method: post }

admin_cruceros_search_cities:
    pattern:  /search/cities/{country}
    defaults: { _controller: "CruceoUserBundle:Cruceros:searchCities", _format: json|html }
    requirements: { _method: post }

admin_cruceros_search_countries:
    pattern:  /search/countries
    defaults: { _controller: "CruceoUserBundle:Cruceros:searchCountries", _format: json|html }
    requirements: { _method: post }