admin_navieras:
    pattern:  /
    defaults: { _controller: "CruceoUserBundle:Navieras:index" }

admin_navieras_new:
    pattern:  /new
    defaults: { _controller: "CruceoUserBundle:Navieras:new" }

admin_navieras_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CruceoUserBundle:Navieras:edit" }

admin_navieras_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CruceoUserBundle:Navieras:delete" }
    requirements: { _method: post }