admin_index:
  pattern:  /admin
  defaults: { _controller: CruceoUserBundle:Admin:index }

admin_cruceros:
  pattern:  /admin/cruceros
  defaults: { _controller: CruceoUserBundle:Admin:cruceros }
  
admin_user:
  pattern:  /newuser
  defaults: { _controller: CruceoUserBundle:Admin:user }