#
# Routing admin
#
admin_index:
  pattern:  /admin
  defaults: { _controller: CruceoUserBundle:Admin:index }

admin_user:
  pattern:  /newuser
  defaults: { _controller: CruceoUserBundle:Admin:user }

login:
  pattern: /admin/login
  defaults: { _controller: CruceoUserBundle:Admin:login }

logout:
  pattern: /admin/logout
  defaults: { _controller: CruceoUserBundle:Admin:logout }

login_check:
  pattern: /admin/login_check
  defaults: { _controller: CruceoUserBundle:Admin:loginCheck }

#
# Routing components
#
CruceoUserBundle_admin_ciudades:
    resource: "@CruceoUserBundle/Resources/config/routing/ciudades.yml"
    prefix:   /admin/ciudades

CruceoUserBundle_admin_navieras:
    resource: "@CruceoUserBundle/Resources/config/routing/navieras.yml"
    prefix:   /admin/navieras

CruceoUserBundle_admin_zonas:
    resource: "@CruceoUserBundle/Resources/config/routing/zonas.yml"
    prefix:   /admin/zonas

CruceoUserBundle_admin_categorias:
    resource: "@CruceoUserBundle/Resources/config/routing/categorias.yml"
    prefix:   /admin/categorias

CruceoUserBundle_admin_agencias:
    resource: "@CruceoUserBundle/Resources/config/routing/agencias.yml"
    prefix:   /admin/agencias

CruceoUserBundle_admin_cruceros:
    resource: "@CruceoUserBundle/Resources/config/routing/cruceros.yml"
    prefix:   /admin/cruceros

CruceoUserBundle_admin_barcos:
    resource: "@CruceoUserBundle/Resources/config/routing/barcos.yml"
    prefix:   /admin/barcos

CruceoUserBundle_admin_tipologias:
    resource: "@CruceoUserBundle/Resources/config/routing/tipologias.yml"
    prefix:   /admin/tipos

CruceoUserBundle_admin_equipamientos:
    resource: "@CruceoUserBundle/Resources/config/routing/equipamientos.yml"
    prefix:   /admin/equipamientos

CruceoUserBundle_admin_tipos_lugares:
    resource: "@CruceoUserBundle/Resources/config/routing/tiposLugares.yml"
    prefix:   /admin/tipos-lugares