admin_index:
  pattern:  /admin
  defaults: { _controller: CruceoUserBundle:Admin:index }

admin_cruceros:
  pattern:  /admin/cruceros
  defaults: { _controller: CruceoUserBundle:Admin:cruceros }
  
admin_user:
  pattern:  /newuser
  defaults: { _controller: CruceoUserBundle:Admin:user }

#Ciudades
admin_ciudades:
    pattern:  /admin/ciudades
    defaults: { _controller: "CruceoUserBundle:Ciudades:index" }

admin_ciudades_show:
    pattern:  /admin/ciudades/{id}/show
    defaults: { _controller: "CruceoUserBundle:Ciudades:show" }

admin_ciudades_new:
    pattern:  /admin/ciudades/new
    defaults: { _controller: "CruceoUserBundle:Ciudades:new" }

admin_ciudades_create:
    pattern:  /admin/ciudades/create
    defaults: { _controller: "CruceoUserBundle:Ciudades:create" }
    requirements: { _method: post }

admin_ciudades_edit:
    pattern:  /admin/ciudades/{id}/edit
    defaults: { _controller: "CruceoUserBundle:Ciudades:edit" }

admin_ciudades_update:
    pattern:  /admin/ciudades/{id}/update
    defaults: { _controller: "CruceoUserBundle:Ciudades:update" }
    requirements: { _method: post }

admin_ciudades_delete:
    pattern:  /admin/ciudades/{id}/delete
    defaults: { _controller: "CruceoUserBundle:Ciudades:delete" }
    requirements: { _method: post }

#Navieras
admin_navieras:
    pattern:  /admin/navieras
    defaults: { _controller: "CruceoUserBundle:Navieras:index" }

admin_navieras_show:
    pattern:  /admin/navieras/{id}/show
    defaults: { _controller: "CruceoUserBundle:Navieras:show" }

admin_navieras_new:
    pattern:  /admin/navieras/new
    defaults: { _controller: "CruceoUserBundle:Navieras:new" }

admin_navieras_create:
    pattern:  /admin/navieras/create
    defaults: { _controller: "CruceoUserBundle:Navieras:create" }
    requirements: { _method: post }

admin_navieras_edit:
    pattern:  /admin/navieras/{id}/edit
    defaults: { _controller: "CruceoUserBundle:Navieras:edit" }

admin_navieras_update:
    pattern:  /admin/navieras/{id}/update
    defaults: { _controller: "CruceoUserBundle:Navieras:update" }
    requirements: { _method: post }

admin_navieras_delete:
    pattern:  /admin/navieras/{id}/delete
    defaults: { _controller: "CruceoUserBundle:Navieras:delete" }
    requirements: { _method: post }
